### ISSUE TITLE
Does not show up on top bar

### ISSUE THREAD

**Issue by dbasinge** [ziyagenc/phi#6]
Phi does not show up on top bar after install/configured.

OS: Fedora 40
DE; Gnome 46.1

**Comment by ziyagenc** [comment]
Thanks for opening this issue. 

On GNOME 46, the commit 544ba47 breaks StatsItem in items.js which is used to populate Phi's UI in single instance mode. It is now fixed with the commit 0c5dcaf which also brings a minor enhancement to the notifications.

The new version has been submitted to GNOME Shell Extensions website and should be available soon.
